name: 'Build libheif'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EMSCRIPTEN_VERSION: 1.37.40
    steps:
      - uses: actions/checkout@v2

      - name: Find libheif file
        id: find_file
        run: echo ::set-output name=libheif_file::$(find libheif-*.tar.gz)

      - name: Extract some files
        run: tar -xf ${{ steps.find_file.outputs.libheif_file }}

      - name: Find libheif folder
        id: find_folder
        run: echo ::set-output name=libheif_folder::$(find libheif-* -maxdepth 0 -type d)

      - name: Rename folder
        run: mv ${{ steps.find_folder.outputs.libheif_folder }} libheif

      # - name: Replace build file
      #   run: |
      #     rm libheif/build-emscripten.sh
      #     cp build-emscripten.sh libheif/build-emscripten.sh
      #     chmod +x libheif/build-emscripten.sh

      - name: Install emscripten
        working-directory: libheif
        run: |
          ./scripts/install-ci-linux.sh

      - name: Prepare CI
        working-directory: libheif
        run: |
          ./scripts/prepare-ci.sh

      - name: Run CI
        working-directory: libheif
        run: |
          ./scripts/run-ci.sh

      - name: Copy file
        run: |
          mkdir -p dist
          rm -rf dist/*
          cp libheif/libheif.js dist/libheif.js
          cp libheif/COPYING dist/LICENSE

      - name: List files
        run: ls -a -R

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libheif-js
          path: |
            dist/libheif.js
            dist/LICENSE

  unminify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Install packages
        run: npm ci

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: libheif-js
          path: dist
      
      - name: Unminify libheif
        run: npx unminify dist/libheif.js | sudo tee dist/libheif.code.js

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libheif-code-js
          path: |
            dist/libheif.js
            dist/libheif.code.js
            dist/LICENSE